### ISSUE TITLE
Unable to build the React Project uisng webpack guess plugin

### ISSUE THREAD

**Issue by ajaybeniwal** [guess-js/guess#176]
I am not able to build my react project using the webpack guess plugin with below error 

95% emitting/Users/ajasingh/Work/CXE-UECP/node_modules/webpack-sources/lib/ConcatSource.js:42
			source += typeof child === "string" ? child : child.source();
			                                                    ^

TypeError: child.source is not a function
    at ConcatSource.source (/Users/ajasingh/Work/CXE-UECP/node_modules/webpack-sources/lib/ConcatSource.js:42:56)
    at Compiler.writeOut (/Users/ajasingh/Work/CXE-UECP/node_modules/webpack/lib/Compiler.js:338:26)
    at Compiler.<anonymous> (/Users/ajasingh/Work/CXE-UECP/node_modules/webpack/lib/Compiler.js:328:20)
    at /Users/ajasingh/Work/CXE-UECP/node_modules/webpack/node_modules/async/dist/async.js:3110:16
    at eachOfArrayLike (/Users/ajasingh/Work/CXE-UECP/node_modules/webpack/node_modules/async/dist/async.js:1069:9)
    at eachOf (/Users/ajasingh/Work/CXE-UECP/node_modules/webpack/node_modules/async/dist/async.js:1117:5)
    at Object.eachLimit (/Users/ajasingh/Work/CXE-UECP/node_modules/webpack/node_modules/async/dist/async.js:3172:5)
    at Compiler.emitFiles (/Users/ajasingh/Work/CXE-UECP/node_modules/webpack/lib/Compiler.js:317:20)
    at /Users/ajasingh/Work/CXE-UECP/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ECP@0.0.1 build: `cross-env NODE_ENV=production EQIX_APP=ecp EQIX_ENV=dev webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ECP@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ajasingh/.npm/_logs/2019-07-28T03_21_26_080Z-debug.log

**Comment by mgechev** [comment]
Hey @ajaybeniwal thanks for giving Guess.js a try!

Since React has *very* dynamic route definitions, it's not always possible to parse them ahead of time. To use Guess.js with React, react-router, and react-lodable, you must follow the route definition conventions listed [here](https://github.com/guess-js/guess/tree/master/packages/guess-parser#guess-parser).

Alternatively, feel free to use Guess.js with Next.js, Angular, or Gatsby, where there are no such constraints.
