### ISSUE TITLE
Cannot find source file for FileSaver.min.js error

### ISSUE THREAD

**Issue by naveedahmed1** [guess-js/guess#264]
The latest version of guessjs throws below error:

```
<s> [webpack.Progress] 95% emitting GuessPlugin
(node:25496) UnhandledPromiseRejectionWarning: Error: Cannot find source file for path: D:\Project\ClientApp\node_modules\file-saver\dist\FileSaver.min.js
    at imports (D:\Project\ClientApp\node_modules\guess-parser\dist\guess-parser\index.js:196:15)
    at D:\Project\ClientApp\node_modules\guess-parser\dist\guess-parser\index.js:218:25
    at visitNodes (D:\Project\ClientApp\node_modules\typescript\lib\typescript.js:17016:30)
    at Object.forEachChild (D:\Project\ClientApp\node_modules\typescript\lib\typescript.js:17244:24)
    at SourceFileObject.NodeObject.forEachChild (D:\Project\ClientApp\node_modules\typescript\lib\typescript.js:124873:23)
    at imports (D:\Project\ClientApp\node_modules\guess-parser\dist\guess-parser\index.js:203:8)
    at D:\Project\ClientApp\node_modules\guess-parser\dist\guess-parser\index.js:218:25
    at visitNodes (D:\Project\ClientApp\node_modules\typescript\lib\typescript.js:17016:30)
    at Object.forEachChild (D:\Project\ClientApp\node_modules\typescript\lib\typescript.js:17244:24)
    at SourceFileObject.NodeObject.forEachChild (D:\Project\ClientApp\node_modules\typescript\lib\typescript.js:124873:23)
    at imports (D:\Project\ClientApp\node_modules\guess-parser\dist\guess-parser\index.js:203:8)
    at D:\Project\ClientApp\node_modules\guess-parser\dist\guess-parser\index.js:218:25
    at visitNodes (D:\Project\ClientApp\node_modules\typescript\lib\typescript.js:17016:30)
    at Object.forEachChild (D:\Project\ClientApp\node_modules\typescript\lib\typescript.js:17244:24)
    at SourceFileObject.NodeObject.forEachChild (D:\Project\ClientApp\node_modules\typescript\lib\typescript.js:124873:23)
    at imports (D:\Project\ClientApp\node_modules\guess-parser\dist\guess-parser\index.js:203:8)
(node:25496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Build has been canceled.D:\Project\MyProject.csproj(105,5): Warning MSB5021: Terminating the task executable "cmd" and its child processes because the build was canceled.
A task was canceled.
```

**Version**
```
    "guess-parser": "0.4.11",
    "guess-webpack": "0.4.11",
```

**OS**
Windows

**Comment by mgechev** [comment]
Fixed by https://github.com/guess-js/guess/commit/2e99172a30c59929322a84308a9011ca49877adf.
