### ISSUE TITLE
TypeError: Cannot read property 'tapAsync' of undefined

### ISSUE THREAD

**Issue by praveentcom** [guess-js/guess#281]
There was an issue when I ran 'npm build' in the Angular 8 project.

[error] TypeError: Cannot read property 'tapAsync' of undefined
    at GuessPlugin.apply (D:\ESA\node_modules\guess-webpack\dist\guess-webpack\main.js:476:41)
    at webpack (D:\ESA\node_modules\webpack\lib\webpack.js:51:13)
    at createWebpack (D:\ESA\node_modules\@angular-devkit\build-webpack\src\webpack\index.js:19:74)
    at Object.runWebpack (D:\ESA\node_modules\@angular-devkit\build-webpack\src\webpack\index.js:27:12)
    at rxjs_1.from.pipe.operators_1.mergeScan.success (D:\ESA\node_modules\@angular-devkit\build-angular\src\browser\index.js:125:40)
    at MergeScanSubscriber._next (D:\ESA\node_modules\rxjs\internal\operators\mergeScan.js:57:23)
    at MergeScanSubscriber.Subscriber.next (D:\ESA\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (D:\ESA\node_modules\rxjs\internal\util\subscribeToArray.js:5:20)
    at Observable._trySubscribe (D:\ESA\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (D:\ESA\node_modules\rxjs\internal\Observable.js:30:22)
    at MergeScanOperator.call (D:\ESA\node_modules\rxjs\internal\operators\mergeScan.js:31:23)
    at Observable.subscribe (D:\ESA\node_modules\rxjs\internal\Observable.js:25:31)
    at BufferCountOperator.call (D:\ESA\node_modules\rxjs\internal\operators\bufferCount.js:36:23)
    at Observable.subscribe (D:\ESA\node_modules\rxjs\internal\Observable.js:25:31)
    at SwitchMapOperator.call (D:\ESA\node_modules\rxjs\internal\operators\switchMap.js:33:23)
    at Observable.subscribe (D:\ESA\node_modules\rxjs\internal\Observable.js:25:31)

**Comment by mgechev** [comment]
Would you provide a minimal demo where I can reproduce the issue?

**Comment by castillo05** [comment]
Hello, I had the same problem and I solved it by updating the angular version in my project.

**Comment by castillo05** [comment]
ng update @angular/cli @angular/core --allow-dirty

**Comment by darrylsepeda** [comment]
I encounter same issue with NextJS 9.0.2 ReactJS

```
(node:5074) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tapAsync' of undefined
    at GuessPlugin.apply (/Users/x/Documents/Github/eweddings/node_modules/guess-webpack/dist/guess-webpack/main.js:475:41)
    at webpack (/Users/x/Documents/Github/eweddings/node_modules/next/node_modules/webpack/lib/webpack.js:49:13)
    at /Users/x/Documents/Github/eweddings/node_modules/next/node_modules/webpack/lib/webpack.js:36:39
    at Array.map (<anonymous>)
    at webpack (/Users/x/Documents/Github/eweddings/node_modules/next/node_modules/webpack/lib/webpack.js:36:24)
    at HotReloader.start (/Users/x/Documents/Github/eweddings/node_modules/next/dist/server/hot-reloader.js:15:1778)
    at DevServer.prepare (/Users/x/Documents/Github/eweddings/node_modules/next/dist/server/next-dev-server.js:6:1199)
(node:5074) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5074) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by coderdix** [comment]
> I encounter same issue with NextJS 9.0.2 ReactJS
> 
> ```
> (node:5074) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tapAsync' of undefined
>     at GuessPlugin.apply (/Users/x/Documents/Github/eweddings/node_modules/guess-webpack/dist/guess-webpack/main.js:475:41)
>     at webpack (/Users/x/Documents/Github/eweddings/node_modules/next/node_modules/webpack/lib/webpack.js:49:13)
>     at /Users/x/Documents/Github/eweddings/node_modules/next/node_modules/webpack/lib/webpack.js:36:39
>     at Array.map (<anonymous>)
>     at webpack (/Users/x/Documents/Github/eweddings/node_modules/next/node_modules/webpack/lib/webpack.js:36:24)
>     at HotReloader.start (/Users/x/Documents/Github/eweddings/node_modules/next/dist/server/hot-reloader.js:15:1778)
>     at DevServer.prepare (/Users/x/Documents/Github/eweddings/node_modules/next/dist/server/next-dev-server.js:6:1199)
> (node:5074) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:5074) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

Same here, did you ever find a solution?
